title: tawmae
theme: just-the-docs

url: https://just-the-docs.github.io

favicon_ico: "/assets/media/favicon.ico"

ga_tracking: G-E3GPLL6JPF
ga_tracking_anonymize_ip: true

#aux_links:
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: dark

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: Info
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
