title: tawmae
description: A collection of Streamer.bot extensions
og:image: https://tawmae.github.io/assets/media/sb_title.png
theme: just-the-docs

url: https://tawmae.github.io/

logo: "/assets/general/logo.png"
favicon_ico: "/assets/media/favicon.ico"

color_scheme: foo

aux_links:
  "Need help?":
    - "discord_link_placeholder"


#aux_links:
  #"Need help? ↪️":
   # - "https://discord.gg/gEm5UMSvYs"
   

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "StreamerBot extensions by tawmae"

enable_copy_code_button: true

ga_tracking: G-E3GPLL6JPF
ga_tracking_anonymize_ip: true

#aux_links:
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template



callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: Info
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
